### ISSUE TITLE
[feat] Calendar 기능 상세 구현

### ISSUE THREAD

**Issue by annapo99** [folio-world/swift-folio-monorepo#19]
### ✅ Todo
- [x] 각 달의 시작일 종료일 추가
- [x] Item들을 Cell로 변경
- [x] Trade Detail Page에서 Image 보여주기
- [x] 캘린더 날짜 선택시, 색상 변경
- [x] 캘린더 셀의 리스트 3개로 제한
