### ISSUE TITLE
[feat] portfolio UI 구현

### ISSUE THREAD

**Issue by annapo99** [folio-world/swift-folio-monorepo#22]
### ✅ Todo
- [x] portfolio 화면 잡기
- [ ] ticker detail 페이지에서 ticker 수정 & 삭제
- [ ] ticker detail 페이지에서 trade 수정 & 삭제
- [ ] ticker detail 페이지에서 current volume, current price 추가
